import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "./components/SideBar";
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="flex flex-col">
          <>
            <TopBar />
            <SideBar />

            <div className="pt-16 pl-56 transition-all duration-[400ms]">
              {children}
            </div>
          </>
        </body>
      </html>
    </>
  );
}
