"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
// import PrivateRoute from "../pages/PrivateRoute";
import { UserAuthContextProvider } from "../pages/UserAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="flex flex-col">
          <UserAuthContextProvider>
            {/* <PrivateRoute> */} <Navbar />
            {children}
            {/* </PrivateRoute> */}
          </UserAuthContextProvider>
        </body>
      </html>
    </>
  );
}
