"use client";
import { Inter } from "next/font/google";
import SideBar from "../components/SideBar";
import { useState, useEffect, Fragment } from "react";
import TopBar from "../components/TopBar";
import { Transition } from "@headlessui/react";
import { UserAuthContextProvider } from "../components/UserAuthContext";
// import PrivateRoute from "./components/PrivateRoute";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showNav, setShowNav] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  function handleResize() {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  }

  useEffect(() => {
    if (typeof window != undefined) {
      addEventListener("resize", handleResize);
    }

    return () => {
      removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <html lang="en">
        <body className="flex flex-col">
          <div>{children}</div>
        </body>
      </html>
    </>
  );
}
